/**
 * Data access for the UI phase. Every screen reads through these functions,
 * so replacing fixtures with the Player API changes this file only.
 * Enrolment, setup answers and progress are client-side (src/lib/enrollment.ts,
 * src/lib/course-progress.ts) until the API exists.
 */
import learnerJson from "@lms/fixtures/learner.json";
import coursesJson from "@lms/fixtures/courses.json";
// Build Your First AI Agent (generated by fixtures/scripts/build-ai-agent.mjs)
import agentM1 from "@lms/fixtures/module-ai-agent-m1.json";
import agentM2 from "@lms/fixtures/module-ai-agent-m2.json";
import agentM3 from "@lms/fixtures/module-ai-agent-m3.json";
import agentM4 from "@lms/fixtures/module-ai-agent-m4.json";
import agentM5 from "@lms/fixtures/module-ai-agent-m5.json";
import agentM6 from "@lms/fixtures/module-ai-agent-m6.json";
import agentVideos from "@lms/fixtures/videos-ai-agent.json";
import agentIntro from "@lms/fixtures/intro-ai-agent.json";
import agentPrecheck from "@lms/fixtures/precheck-ai-agent.json";
import agentFinale from "@lms/fixtures/finale-ai-agent.json";
import agentProject from "@lms/fixtures/project-ai-agent.json";
import type { ConceptVideo, Course, CourseModule, ExplainerBlock, FinaleContent, GuidedBlock, Learner, ModuleContent, PrecheckContent, ProjectContent } from "./types";

const learner = learnerJson as unknown as Learner;
const baseCourses = (coursesJson as unknown as { courses: Course[] }).courses;

/*
 * Course content, registered per course. To add a course, put it in
 * fixtures/courses.json, then import its content files here and add them to
 * the lists below. Every entry carries its course_id, so module ids such as
 * "m1" can repeat across courses.
 */
/** Modules written in full, every topic included. */
const fullModules: ModuleContent[] = [agentM1, agentM2, agentM3, agentM4, agentM5, agentM6].map((m) => m as unknown as ModuleContent);
/** Narrated concept videos (audio: /audio/video-{id}-s{n}.mp3), one list per course. */
const courseVideos: { course_id: string; videos: ConceptVideo[] }[] = [agentVideos as unknown as { course_id: string; videos: ConceptVideo[] }];
/** Guided practice written for modules that are otherwise concept-only. */
const guided: { course_id: string; module_id: string; block: GuidedBlock }[] = [];
const finales: FinaleContent[] = [agentFinale as unknown as FinaleContent];
const prechecks: PrecheckContent[] = [agentPrecheck as unknown as PrecheckContent];
/** The mini project workspace, for courses whose project is built in the browser. */
const projects: ProjectContent[] = [agentProject as unknown as ProjectContent];
/** The course preview video shown while enrolling, between "About you" and the quick check. */
const intros: { course_id: string; video: ConceptVideo }[] = [agentIntro as unknown as { course_id: string; video: ConceptVideo }];

function videosFor(courseId: string, moduleId: string): ConceptVideo[] {
  return (courseVideos.find((v) => v.course_id === courseId)?.videos ?? []).filter((v) => v.module === moduleId);
}

/** A fully written module's concept topic is taught by its videos when it has them. */
function withVideos(mod: ModuleContent): ModuleContent {
  const vids = videosFor(mod.course_id, mod.module_id);
  if (!vids.length) return mod;
  return {
    ...mod,
    blocks: mod.blocks.map((b) => (b.stage === "explainer" ? ({ ...b, videos: vids } as ExplainerBlock) : b)),
  };
}

/** Other modules: their concept topic (the narrated videos), plus guided practice where it is written. */
function conceptOnly(course: Course, m: CourseModule): ModuleContent | null {
  const vids = videosFor(course.course_id, m.module_id);
  if (!vids.length) return null;
  const words = vids.reduce((n, v) => n + v.slides.reduce((k, s) => k + s.narration.split(/\s+/).length, 0), 0);
  const minutes = Math.round(words / 150) + vids.length; // narration at ~150 wpm, plus a minute of checks per video
  const objectives = m.lessons.map((l) => ({ id: `obj-${l.id}`, text: l.title, lesson: l.id }));
  const practice = guided.find((g) => g.course_id === course.course_id && g.module_id === m.module_id)?.block;
  return {
    course_id: course.course_id,
    course_title: course.title,
    module_id: m.module_id,
    version: "1.0.0",
    locale: "en",
    title: m.title,
    summary: m.pain,
    estimated_minutes: minutes + (practice?.duration_min ?? 0),
    stages_included: practice ? ["explainer", "guided"] : ["explainer"],
    metadata: { objectives },
    blocks: [
      {
        step_id: `${m.module_id}.explain`,
        stage: "explainer",
        duration_min: minutes,
        bloom: "understand",
        load: "medium",
        objective_ids: objectives.map((o) => o.id),
        concepts: [],
        segments: [],
        videos: vids,
      } as ExplainerBlock,
      ...(practice ? [practice] : []),
    ],
  };
}

const isFull = (courseId: string, moduleId: string) => fullModules.some((f) => f.course_id === courseId && f.module_id === moduleId);

const authored: ModuleContent[] = [
  ...fullModules.map(withVideos),
  ...baseCourses
    .flatMap((c) => c.modules.filter((m) => !isFull(c.course_id, m.module_id)).map((m) => conceptOnly(c, m)))
    .filter((m): m is ModuleContent => !!m),
];

// every module records which of its topics have content, so links go to a playable topic
const courses: Course[] = baseCourses.map((c) => ({
  ...c,
  modules: c.modules.map((m) => ({
    ...m,
    authored: authored.find((a) => a.course_id === c.course_id && a.module_id === m.module_id)?.stages_included ?? [],
  })),
}));

/** "Today" for the fixtures, so due dates and greetings stay stable. */
export const FIXTURE_TODAY = "2026-10-07";

export async function getLearner(): Promise<Learner> {
  return learner;
}

export async function getCourses(): Promise<Course[]> {
  return courses;
}

export async function getCourse(courseId: string): Promise<Course | undefined> {
  return courses.find((c) => c.course_id === courseId);
}

/** Module lesson content: full modules, or a module's concept videos and guided practice. */
export async function getModule(courseId: string, moduleId: string): Promise<ModuleContent | undefined> {
  return authored.find((m) => m.course_id === courseId && m.module_id === moduleId);
}

/** Ids of the modules that have lesson content. */
export async function getAuthoredModuleIds(courseId: string): Promise<string[]> {
  return authored.filter((m) => m.course_id === courseId).map((m) => m.module_id);
}

/** The course finale: capstone, final check and wrap-up, taken after all modules. */
export async function getFinale(courseId: string): Promise<FinaleContent | undefined> {
  return finales.find((f) => f.course_id === courseId);
}

/** The ungraded pre-check asked once, before Module 1. */
export async function getPrecheck(courseId: string): Promise<PrecheckContent | undefined> {
  return prechecks.find((p) => p.course_id === courseId);
}

/** The mini project workspace (files and sample tickets), if the course has one. */
export async function getProject(courseId: string): Promise<ProjectContent | undefined> {
  return projects.find((p) => p.course_id === courseId);
}

/** The course preview video, if the course has one. */
export async function getCourseIntro(courseId: string): Promise<ConceptVideo | undefined> {
  return intros.find((i) => i.course_id === courseId)?.video;
}

export { getBlock } from "./client";
